theme: minima
title: Welcome to my portfolio!
author: Uyen Dang
email: mqt129(at)gmail
description: > # this means to ignore newlines until "baseurl:"
  I am a junior developer and this is my awesome portfolio!!!!

# social links
twitter_username: uyentdang12 # DO NOT include the @ character, or else the build will fail!
github_username:  uyentdang # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
